spring.application.name=cqrs


# =========================
# MYSQL COMMAND DATABASE
# =========================

spring.datasource.command.url=${DB_COMMAND_URL_SQL}
spring.datasource.command.username=${DB_COMMAND_USER}
spring.datasource.command.password=${DB_COMMAND_PASSWORD}
spring.datasource.command.driver-class-name=com.mysql.cj.jdbc.Driver

spring.flyway.enabled=false


# =========================
# MYSQL QUERY DATABASE
# =========================

spring.datasource.query.url=${DB_QUERY_URL_SQL}
spring.datasource.query.username=${DB_QUERY_USER}
spring.datasource.query.password=${DB_QUERY_PASSWORD}
spring.datasource.query.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================
# JPA
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=OFF


# =========================
# FLYWAY (mantido temporariamente)
# =========================

#spring.flyway.enabled=true


# ========================
# GOOGLE
# ========================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_URL}


# =========================
# COOKIES + JWT
# =========================

app.cookie.name=${COOKIE_NAME}
app.cookie.max-age=${COOKIE_MAX_AGE}
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS}

app.security.email-admin=${MY_EMAIL_ADMIN}

app.refresh-token.expiration-ms=604800000
app.refresh-token.cookie-name=refresh_token


# =========================
# KAFKA
# =========================

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN


spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer


spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.properties.spring.json.trusted.packages=com.project.cqrs.shared.event.*
spring.kafka.consumer.properties.spring.json.use.type.headers=true


# ===========================
# Pageable
# ===========================

spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.max-page-size=100
spring.data.web.pageable.one-indexed-parameters=false


# ==========================
# Spring Threads
# ==========================

spring.threads.virtual.enabled=true

spring.datasource.hikari.maximum-pool-size=100

server.tomcat.threads.max=8


# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.metrics.access=unrestricted


# ========================
# REDIS CACHE
# ========================

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}


# Lettuce Pool

spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=2
spring.data.redis.lettuce.pool.max-wait=-1ms
spring.data.redis.lettuce.shutdown-timeout=100ms


# Cache

spring.cache.type=redis
spring.cache.redis.time-to-live=600000
spring.cache.redis.cache-null-values=false
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=cqrs:

spring.data.redis.repositories.enabled=false


# Cache TTL customizados

app.cache.product-list-ttl=300000
app.cache.product-detail-ttl=600000
app.cache.category-list-ttl=900000


# ========================
# SWAGGER
# ========================

springdoc.swagger-ui.path=/swagger
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.api-docs.path=/api-docs


# =====================
# EMAIL
# =====================

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=${MAIL_FROM:no-reply@seudominio.com.br}
app.mail.from-name=${MAIL_FROM_NAME:Sua Loja}

# =====================
# MERCADO PAGO
# =====================

app.base-url="https://cdfc-2804-4b0-1236-5400-a5ff-6d03-4915-8670.ngrok-free.app/api/v1/webhooks"
mp.webhook-secret="3a68ff1f953359e80c8ca5a05ec70a0e2ad8c0944272691414bb240702e5552c"
mp.access-token="APP_USR-5685054857415198-111010-c414aa734c3e649ebed4485a5a08d8f8-2410150893"
mp.public-key="APP_USR-f2838fd2-9231-4ce9-8855-a5155a886fc5"